In [1]:
import pandas as pd

In [2]:
# importing data 
df= pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  3900 non-null   int64
 1   age                          3900 non-null   int64
 2   gender                       3900 non-null   object
 3   item_purchased               3900 non-null   object
 4   category                     3900 non-null   object
 5   purchase_amount              3900 non-null   int64
 6   location                     3900 non-null   object
 7   size                         3900 non-null   object
 8   color                        3900 non-null   object
 9   season                       3900 non-null   object
 10  review_rating                3900 non-null   float64
 11  subscription_status          3900 non-null   object
 12  shipping_type                3900 non-null   object
 13  discount_applied             3900 non-null   object
 14  previous_purchases           3900 non-null   int64
 15  payment_method               3900 non-null   object
 16  frequency_of_purchases       3900 non-null   object
 17  Age_groups                   3900 non-null   category
 18  frequency_of_purchases_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), object(12)
memory usage: 552.6+ KB

In [23]:
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,frequency_of_purchases_days
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750051,25.351538,78.161795
std,1125.977353,15.207589,23.685392,0.713590,14.447125,121.920244
min,1.000000,18.000000,20.000000,2.500000,1.000000,7.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,14.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,14.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,90.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000

In [24]:
# need to check all categorical column also 
df.describe(include='all')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,Age_groups,frequency_of_purchases_days
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,NaN,6,7,4,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,NaN,PayPal,Every 3 Months,Young-Adult,NaN
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,NaN,677,584,1028,NaN
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750051,NaN,NaN,NaN,25.351538,NaN,NaN,NaN,78.161795
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.713590,NaN,NaN,NaN,14.447125,NaN,NaN,NaN,121.920244
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,7.000000
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,14.000000
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,14.000000
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,90.000000
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,365.000000

In [25]:
# missing values 
df.isnull().sum()

customer_id                    0
age                            0
gender                         0
item_purchased                 0
category                       0
purchase_amount                0
location                       0
size                           0
color                          0
season                         0
review_rating                  0
subscription_status            0
shipping_type                  0
discount_applied               0
previous_purchases             0
payment_method                 0
frequency_of_purchases         0
Age_groups                     0
frequency_of_purchases_days    0
dtype: int64

We can see 37 null values in "Review Rating" columns . So we are going to fill it with median values with respective category using groupby .

In [27]:
df["review_rating"]=df.groupby('category')["review_rating"].transform(lambda x : x.fillna(x.median()))

In [28]:
# rechecking the missing values 
df.isnull().sum()

customer_id                    0
age                            0
gender                         0
item_purchased                 0
category                       0
purchase_amount                0
location                       0
size                           0
color                          0
season                         0
review_rating                  0
subscription_status            0
shipping_type                  0
discount_applied               0
previous_purchases             0
payment_method                 0
frequency_of_purchases         0
Age_groups                     0
frequency_of_purchases_days    0
dtype: int64

- Now we can see that some column names have space , Upper case which may be problemetic during sql and writing names . So we will convert them into sneak casing (combination of lower case & "_") . 
- We are going to us .str beacuse 
   - df.columns is NOT a single string
   - .columns = collection of strings
   - .lower() works only on one string at a time
   - .str is a vectorized string accessor
   - .strip() => Removes extra spaces from beginning and end

In [29]:
df.columns = df.columns.str.lower().str.replace(" ", "_").str.strip()

# renaming the column name 
df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'},inplace =True)

In [30]:
# rechecking the restructered column name  
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_groups', 'frequency_of_purchases_days'],
      dtype='object')

- To understand the market and purchasing behaviour  we are coenverting the 'age'  as 'age_groups' .
- qcut() => Equal number of rows per bin
- Syntax : pd.qcut(data, q)

In [31]:
labels = ['Young-Adult','Adult','Middle-Aged','Seniors']
df["Age_groups"]=pd.qcut(df["age"],q=4,labels=labels)
df[['age','Age_groups']].tail(10)

      age   Age_groups
3890   35        Adult
3891   36        Adult
3892   35        Adult
3893   21  Young-Adult
3894   66      Seniors
3895   40        Adult
3896   52  Middle-Aged
3897   46  Middle-Aged
3898   44        Adult
3899   52  Middle-Aged

In [32]:
unique=df['frequency_of_purchases'].value_counts()
unique

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [33]:
frequency_maping = {
 'Fortnightly'    : 14,
 'Every 3 Months' : 90,
 'Annually'       :365,
 'Quarterly'      :14,
 'Monthly'        :30,
 'Bi-Weekly'      :14, 
 'Weekly'         :7    
}

# create new column frequency_of_purchases_days
df["frequency_of_purchases_days"] = df["frequency_of_purchases"].map(frequency_maping)
df[["frequency_of_purchases_days","frequency_of_purchases"]]

      frequency_of_purchases_days frequency_of_purchases
0                              14            Fortnightly
1                              14            Fortnightly
2                               7                 Weekly
3                               7                 Weekly
4                             365               Annually
...                           ...                    ...
3895                            7                 Weekly
3896                           14              Bi-Weekly
3897                           14              Quarterly
3898                            7                 Weekly
3899                           14              Quarterly

[3900 rows x 2 columns]

In [34]:
df[['discount_applied','promo_code_used']].head(10)

KeyError: "['promo_code_used'] not in index"

In [15]:
# checking that 'discount_applied' & 'promo_code_used' is same or not , so thta we can process with one value 

(df['discount_applied'] == df['promo_code_used']).all()

True

In [16]:
df=df.drop('promo_code_used',axis=1)

In [17]:
# rechecking the restructered column name  
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'Age_groups', 'frequency_of_purchases_days'],
      dtype='object')

## Connecting Python script to SQL

## Code for MySQL

In [18]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in d:\data science\data science omkar\anaconda\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in d:\data science\data science omkar\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\data science\data science omkar\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\data science\data science omkar\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)

In [19]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# mySql connection 
connection_url = URL.create(
    "mysql+pymysql",
    username="root",
    password="mohapatra@1998",
    host="localhost",
    port=3306,
    database="customer_behavior"
)

engine = create_engine(connection_url)
df.to_sql("customer", engine, if_exists="replace", index=False)

# Read back sample 
pd.read_sql("SELECT * FROM customer LIMIT 10 ;",engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,Age_groups,frequency_of_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young-Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young-Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-Aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Seniors,14
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young-Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young-Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-Aged,14